In [2]:
import pandas as pd
import joblib
import time

In [3]:
movies = pd.read_pickle("../models/movies.pkl")

knn = joblib.load("../models/recommendation_model.pkl")

movie_index = joblib.load(
    "../models/movie_index.pkl"
)
tfidf_matrix = joblib.load("../models/tfidf_matrix.pkl")

In [15]:
def recommend(

    movie_name,

    start=0,

    limit=20

):

    movie_name = movie_name.lower()

    if not movie_name:
        return "Movie not found."

    if movie_name not in movie_index:
        return "Movie not found."

    idx = movie_index[movie_name]

    distances, indices = knn.kneighbors(

        tfidf_matrix[idx],

        n_neighbors=start+limit+1

    )

    indices = indices[0][1:]

    distances = distances[0][1:]

    recommendations = movies.iloc[indices].copy()
    recommendations["similarity"] = 1 - distances

    return recommendations.iloc[start:start+limit][

        [

            "title",

            "release_year",

            "avg_rating",

            "genres",

            "similarity",

            "poster_url"

        ]

    ]

In [5]:
test_movies = [
    "Interstellar",
    "Inception",
    "The Dark Knight",
    "Parasite",
    "Barbie",
    "Avengers: Endgame",
    "Dangal",
    "3 Idiots",
    "The Godfather",
    "Titanic"
]

In [6]:
for movie in test_movies:

    print("="*80)

    print(f"Movie : {movie}\n")

    print(recommend(movie, limit=10))

================================================================================
Movie : Interstellar

                      title  release_year  avg_rating  \
3839                Solaris        2002.0        3.25
5448                 Aniara        2018.0        3.54
988                    Moon        2009.0        3.86
1603                Contact        1997.0        3.78
7037                 Vesper        2022.0        3.12
2627    On the Silver Globe        1988.0        4.02
948                 Solaris        1972.0        4.24
5797                  K-PAX        2001.0        3.28
6803        The Quiet Earth        1985.0        3.49
108   2001: A Space Odyssey        1968.0        4.30

                                       genres  similarity  \
3839            mystery science fiction drama    0.479169
5448                    science fiction drama    0.467531
988                     science fiction drama    0.443856
1603            science fiction mystery drama    0.441785
7037  science fiction drama adventure fantasy    0.433533
2627                    drama science fiction    0.419127
948             mystery science fiction drama    0.418524
5797            science fiction mystery drama    0.417632
6803           drama science fiction thriller    0.416983
108         adventure mystery science fiction    0.416338

                                             poster_url
3839  https://a.ltrbxd.com/resized/film-poster/5/0/5...
5448  https://a.ltrbxd.com/resized/film-poster/4/2/6...
988   https://a.ltrbxd.com/resized/sm/upload/1z/15/k...
1603  https://a.ltrbxd.com/resized/film-poster/5/1/4...
7037  https://a.ltrbxd.com/resized/film-poster/8/7/8...
2627  https://a.ltrbxd.com/resized/film-poster/3/4/8...
948   https://a.ltrbxd.com/resized/film-poster/5/1/5...
5797  https://a.ltrbxd.com/resized/film-poster/5/1/8...
6803  https://a.ltrbxd.com/resized/film-poster/4/6/4...
108   https://a.ltrbxd.com/resized/sm/upload/fe/jp/4...
================================================================================
Movie : Inception

                                   title  release_year  avg_rating  \
71                    Mad Max: Fury Road        2015.0        4.19
131                                Tenet        2020.0        3.40
5096                              Zardoz        1974.0        3.21
808                               Looper        2012.0        3.56
813    Kingdom of the Planet of the Apes        2024.0        3.40
1098                                Dune        1984.0        2.78
139                             Iron Man        2008.0        3.70
1381           It's Such a Beautiful Day        2012.0        4.38
11163                The Midnight Gospel        2020.0        4.33
6                           Interstellar        2014.0        4.35

                                        genres  similarity  \
71            adventure science fiction action    0.342519
131            action thriller science fiction    0.318269
5096   fantasy science fiction action thriller    0.305245
808            science fiction thriller action    0.300441
813           adventure science fiction action    0.297339
1098          adventure science fiction action    0.296059
139           adventure science fiction action    0.292872
1381                          comedy animation    0.292826
11163                 mystery animation comedy    0.292318
6              science fiction drama adventure    0.278545

                                              poster_url
71     https://a.ltrbxd.com/resized/film-poster/6/2/7...
131    https://a.ltrbxd.com/resized/sm/upload/pq/9f/s...
5096   https://a.ltrbxd.com/resized/film-poster/4/9/0...
808    https://a.ltrbxd.com/resized/sm/upload/qp/zb/l...
813    https://a.ltrbxd.com/resized/film-poster/5/7/8...
1098   https://a.ltrbxd.com/resized/sm/upload/e9/3l/l...
139    https://a.ltrbxd.com/resized/film-poster/5/0/8...
1381   https://a.ltrbxd.com/resized/sm/upload/on/mj/o...
11163  https://a.ltrbxd.com/resized/film-poster/7/9/4...
6      https://a.ltrbxd.com/resized/film-poster/1/1/7...
================================================================================
Movie : The Dark Knight

                                          title  release_year  avg_rating  \
169                               Batman Begins        2005.0        3.80
159                       The Dark Knight Rises        2012.0        3.74
12                                   The Batman        2022.0        3.98
118739         Batman Begins - Behind the Story           NaN         NaN
1394                             Batman Forever        1995.0        2.46
837                              Batman Returns        1992.0        3.55
3656    Batman: The Dark Knight Returns, Part 1        2012.0        3.81
1768                               End of Watch        2012.0        3.72
2925                   Batman: The Killing Joke        2016.0        2.80
4563                       The Batman - Part II        2026.0         NaN

                                          genres  similarity  \
169                           crime action drama    0.510476
159                  thriller drama crime action    0.452640
12                        crime mystery thriller    0.267917
118739                               documentary    0.266922
1394                        fantasy crime action    0.260823
837                               fantasy action    0.242550
3656    animation mystery science fiction action    0.236951
1768                        thriller crime drama    0.234451
2925                crime animation drama action    0.229362
4563                          action drama crime    0.229147

                                               poster_url
169     https://a.ltrbxd.com/resized/film-poster/5/1/7...
159     https://a.ltrbxd.com/resized/film-poster/1/6/5...
12      https://a.ltrbxd.com/resized/film-poster/3/4/8...
118739  https://a.ltrbxd.com/resized/film-poster/1/0/9...
1394    https://a.ltrbxd.com/resized/film-poster/5/1/6...
837     https://a.ltrbxd.com/resized/film-poster/5/1/7...
3656    https://a.ltrbxd.com/resized/sm/upload/fj/e7/j...
1768    https://a.ltrbxd.com/resized/film-poster/6/3/4...
2925    https://a.ltrbxd.com/resized/film-poster/3/1/7...
4563    https://a.ltrbxd.com/resized/film-poster/7/2/3...
================================================================================
Movie : Parasite

                                 title  release_year  avg_rating  \
58909             The Poet and the Boy        2017.0        3.28
116872             Officer of the Year        2011.0         NaN
227183                 Black Honeymoon        2000.0         NaN
1837        Sympathy for Mr. Vengeance        2002.0        3.97
391566                    Boy Director        2008.0         NaN
46993                         The Five        2013.0        3.23
102454               All That We Loved        2023.0         NaN
33578                            Cello        2005.0        3.01
28408   Dongju: The Portrait of a Poet        2016.0        3.71
73401              Made on the Rooftop        2020.0        3.21

                        genres  similarity  \
58909                    drama    0.326025
116872           action comedy    0.322432
227183  thriller mystery drama    0.315872
1837     drama thriller action    0.296014
391566            family drama    0.293203
46993           thriller drama    0.292393
102454                   drama    0.287299
33578           horror mystery    0.285223
28408            history drama    0.285037
73401     romance drama comedy    0.279913

                                               poster_url
58909   https://a.ltrbxd.com/resized/film-poster/4/0/1...
116872  https://a.ltrbxd.com/resized/film-poster/5/7/8...
227183  https://a.ltrbxd.com/resized/film-poster/1/9/9...
1837    https://a.ltrbxd.com/resized/sm/upload/v7/7s/n...
391566  https://a.ltrbxd.com/resized/film-poster/4/9/9...
46993   https://a.ltrbxd.com/resized/film-poster/1/6/5...
102454  https://a.ltrbxd.com/resized/film-poster/1/0/2...
33578   https://a.ltrbxd.com/resized/film-poster/3/0/5...
28408   https://a.ltrbxd.com/resized/film-poster/3/1/7...
73401   https://a.ltrbxd.com/resized/film-poster/6/8/2...
================================================================================
Movie : Barbie

                                   title  release_year  avg_rating  \
670                       Swiss Army Man        2016.0        3.66
1381           It's Such a Beautiful Day        2012.0        4.38
1955               Stranger Than Fiction        2006.0        3.61
11163                The Midnight Gospel        2020.0        4.33
77952                              Guilt        2019.0        3.54
4758          Wristcutters: A Love Story        2006.0        3.61
5552              Joe Versus the Volcano        1990.0        3.18
3082                     The Fisher King        1991.0        3.86
179                               Amélie        2001.0        4.17
2      Everything Everywhere All at Once        2022.0        4.30

                                        genres  similarity  \
670     drama fantasy comedy adventure romance    0.324742
1381                          comedy animation    0.292019
1955              drama fantasy romance comedy    0.285200
11163                 mystery animation comedy    0.276632
77952                       comedy crime drama    0.276012
4758              fantasy drama romance comedy    0.274667
5552                            romance comedy    0.262819
3082                              drama comedy    0.261634
179                             romance comedy    0.258950
2      science fiction adventure comedy action    0.257481

                                              poster_url
670    https://a.ltrbxd.com/resized/sm/upload/pp/ya/j...
1381   https://a.ltrbxd.com/resized/sm/upload/on/mj/o...
1955   https://a.ltrbxd.com/resized/film-poster/5/1/1...
11163  https://a.ltrbxd.com/resized/film-poster/7/9/4...
77952  https://a.ltrbxd.com/resized/film-poster/5/7/5...
4758   https://a.ltrbxd.com/resized/film-poster/4/4/0...
5552   https://a.ltrbxd.com/resized/sm/upload/ve/x4/y...
3082   https://a.ltrbxd.com/resized/sm/upload/px/zw/7...
179    https://a.ltrbxd.com/resized/sm/upload/ly/0v/e...
2      https://a.ltrbxd.com/resized/film-poster/4/7/4...
================================================================================
Movie : Avengers: Endgame

                                                title  release_year  \
199                           Avengers: Age of Ultron        2015.0
114                                      The Avengers        2012.0
39                             Avengers: Infinity War        2018.0
152                        Captain America: Civil War        2016.0
175               Captain America: The Winter Soldier        2014.0
287                                        Iron Man 3        2013.0
297                                        Iron Man 2        2010.0
120154  Marvel Studios: Building a Cinematic Universe        2012.0
15237                    Ultimate Avengers: The Movie        2006.0
21430                         The Invincible Iron Man        2007.0

        avg_rating                                             genres  \
199           3.10                   action adventure science fiction
114           3.65                   science fiction adventure action
39            3.96                   action science fiction adventure
152           3.57                   action science fiction adventure
175           3.71                   adventure science fiction action
287           3.01                   action adventure science fiction
297           2.87                   adventure science fiction action
120154         NaN                                        documentary
15237         2.97  animation action adventure science fiction family
21430         2.69  science fiction fantasy animation action adven...

        similarity                                         poster_url
199       0.663348  https://a.ltrbxd.com/resized/film-poster/8/1/6...
114       0.602495  https://a.ltrbxd.com/resized/sm/upload/10/u6/4...
39        0.598023  https://a.ltrbxd.com/resized/film-poster/2/2/6...
152       0.422957  https://a.ltrbxd.com/resized/film-poster/1/9/4...
175       0.356329  https://a.ltrbxd.com/resized/sm/upload/he/p6/c...
287       0.346660  https://a.ltrbxd.com/resized/sm/upload/5r/0i/9...
297       0.341260  https://a.ltrbxd.com/resized/film-poster/4/6/5...
120154    0.329843  https://a.ltrbxd.com/resized/film-poster/1/0/4...
15237     0.304805  https://a.ltrbxd.com/resized/film-poster/4/2/9...
21430     0.303390  https://a.ltrbxd.com/resized/film-poster/4/3/7...
================================================================================
Movie : Dangal

                     title  release_year  avg_rating                genres  \
18970           Dhobi Ghat        2010.0        3.59                 drama
28075        Irudhi Suttru        2016.0        3.49          drama action
30010             Brothers        2015.0        2.73          drama action
13237                 Ludo        2020.0        3.41          crime comedy
27109   Thugs of Hindostan        2018.0        2.24      action adventure
7268    Kuch Kuch Hota Hai        1998.0        3.66         romance drama
25398             Mary Kom        2014.0        3.18  history action drama
11284                Udaan        2010.0        3.97                 drama
4292   Like Stars on Earth        2007.0        3.93                 drama
68523                 Apne        2007.0        3.05                 drama

       similarity                                         poster_url
18970    0.280286  https://a.ltrbxd.com/resized/film-poster/1/1/2...
28075    0.247761  https://a.ltrbxd.com/resized/film-poster/2/8/8...
30010    0.222297  https://a.ltrbxd.com/resized/film-poster/2/5/7...
13237    0.222183  https://a.ltrbxd.com/resized/film-poster/5/8/3...
27109    0.220204  https://a.ltrbxd.com/resized/film-poster/4/0/3...
7268     0.219363  https://a.ltrbxd.com/resized/film-poster/4/4/9...
25398    0.217187  https://a.ltrbxd.com/resized/film-poster/2/0/9...
11284    0.216586  https://a.ltrbxd.com/resized/film-poster/1/9/9...
4292     0.214941  https://a.ltrbxd.com/resized/film-poster/4/8/0...
68523    0.212597  https://a.ltrbxd.com/resized/film-poster/6/4/5...
================================================================================
Movie : 3 Idiots

                       title  release_year  avg_rating  \
13557    Munna Bhai M.B.B.S.        2003.0        3.66
26779     Ek Main Aur Ekk Tu        2012.0        2.89
5456                      PK        2014.0        3.72
438    The Edge of Seventeen        2016.0        3.52
4292     Like Stars on Earth        2007.0        3.93
8644           Son of Rambow        2007.0        3.52
15610       Secret Superstar        2017.0        3.37
12360    Student of the Year        2012.0        2.75
8788                 Strike!        1998.0        3.64
18122            The D Train        2015.0        2.63

                             genres  similarity  \
13557                  drama comedy    0.283594
26779          comedy romance drama    0.270054
5456   drama comedy science fiction    0.265782
438                    drama comedy    0.258724
4292                          drama    0.253311
8644                         comedy    0.242011
15610                   music drama    0.241722
12360          drama romance comedy    0.240868
8788                   comedy drama    0.230288
18122                  comedy drama    0.230080

                                              poster_url
13557  https://a.ltrbxd.com/resized/film-poster/3/9/5...
26779  https://a.ltrbxd.com/resized/film-poster/7/1/0...
5456   https://a.ltrbxd.com/resized/film-poster/2/2/4...
438    https://a.ltrbxd.com/resized/film-poster/3/1/1...
4292   https://a.ltrbxd.com/resized/film-poster/4/8/0...
8644   https://a.ltrbxd.com/resized/sm/upload/qg/u9/i...
15610  https://a.ltrbxd.com/resized/film-poster/3/7/4...
12360  https://a.ltrbxd.com/resized/film-poster/1/0/5...
8788   https://a.ltrbxd.com/resized/film-poster/3/9/6...
18122  https://a.ltrbxd.com/resized/film-poster/2/3/5...
================================================================================
Movie : The Godfather

                                     title  release_year  avg_rating  \
228                 The Godfather: Part II        1974.0        4.59
900                The Godfather: Part III        1990.0        3.46
36700  The Godfather Family: A Look Inside        1990.0        3.64
17901                           Blood Ties        2013.0        3.06
9971                       The Rain People        1969.0        3.58
7343                       The Cotton Club        1984.0        3.38
60495                 The Godfather Legacy        2012.0        3.60
1287                          Mean Streets        1973.0        3.71
48564                          The Wee Man        2013.0        2.97
23732                            Adulthood        2008.0        3.11

                     genres  similarity  \
228             crime drama    0.523237
900    drama thriller crime    0.411862
36700  documentary tv movie    0.379458
17901  crime drama thriller    0.314173
9971                  drama    0.279803
7343            drama crime    0.263102
60495  tv movie documentary    0.244325
1287            drama crime    0.230168
48564   crime drama history    0.227819
23732           drama crime    0.227776

                                              poster_url
228    https://a.ltrbxd.com/resized/film-poster/5/1/8...
900    https://a.ltrbxd.com/resized/film-poster/5/1/8...
36700  https://a.ltrbxd.com/resized/film-poster/9/8/7...
17901  https://a.ltrbxd.com/resized/film-poster/1/3/7...
9971   https://a.ltrbxd.com/resized/film-poster/7/1/3...
7343   https://a.ltrbxd.com/resized/sm/upload/zv/bn/v...
60495  https://a.ltrbxd.com/resized/film-poster/2/2/1...
1287   https://a.ltrbxd.com/resized/film-poster/5/1/8...
48564  https://a.ltrbxd.com/resized/film-poster/9/5/8...
23732  https://a.ltrbxd.com/resized/film-poster/4/4/1...
================================================================================
Movie : Titanic

                        title  release_year  avg_rating  \
321681   A Fatherless America           NaN         NaN
13997     Ghosts of the Abyss        2003.0        3.28
18781                 Titanic        1953.0        3.26
130431  Titanic: 100 Years On        2012.0         NaN
4604                   Adrift        2018.0        3.13
52081   The Keys to the House        2004.0        3.47
13341          Rachel, Rachel        1968.0        3.62
2523     Fried Green Tomatoes        1991.0        3.87
1816       Revolutionary Road        2008.0        3.57
11756             Now Is Good        2012.0        3.03

                            genres  similarity  \
321681                         NaN    0.265394
13997                  documentary    0.261428
18781                drama romance    0.259104
130431                 documentary    0.238267
4604    thriller adventure romance    0.235812
52081                        drama    0.229927
13341                drama romance    0.229013
2523                  drama comedy    0.228756
1816                 romance drama    0.223334
11756                romance drama    0.222694

                                               poster_url
321681                                                NaN
13997   https://a.ltrbxd.com/resized/film-poster/3/6/3...
18781   https://a.ltrbxd.com/resized/film-poster/4/1/5...
130431  https://a.ltrbxd.com/resized/film-poster/1/4/2...
4604    https://a.ltrbxd.com/resized/film-poster/3/6/2...
52081   https://a.ltrbxd.com/resized/film-poster/2/2/6...
13341   https://a.ltrbxd.com/resized/film-poster/2/2/4...

In [7]:
times = []

for movie in test_movies:

    start = time.time()

    recommend(movie)

    end = time.time()

    times.append(end-start)

In [8]:
print(f"Average Time : {sum(times)/len(times):.4f} sec")
print(f"Fastest : {min(times):.4f} sec")
print(f"Slowest : {max(times):.4f} sec")

Average Time : 1.5999 sec
Fastest : 1.3631 sec
Slowest : 1.9526 sec

In [9]:
recommend("King Kong")

,title,release_year,avg_rating,genres,similarity,poster_url
2323,King Kong,1933.0,3.86,adventure fantasy horror,0.427465,https://a.ltrbxd.com/resized/sm/upload/oy/yt/b...
7222,King Kong,1976.0,2.93,fantasy adventure,0.347214,https://a.ltrbxd.com/resized/film-poster/4/5/9...
13139,The Son of Kong,1933.0,2.67,action adventure horror,0.330377,https://a.ltrbxd.com/resized/film-poster/2/1/9...
62733,King Kong: Peter Jackson's Production Diaries,2005.0,3.53,documentary,0.319379,https://a.ltrbxd.com/resized/film-poster/6/9/3...
3114,In the Heart of the Sea,2015.0,3.01,drama adventure history thriller action,0.271965,https://a.ltrbxd.com/resized/film-poster/1/4/7...
40737,Jason and the Argonauts,2000.0,2.94,family,0.259428,https://a.ltrbxd.com/resized/film-poster/3/1/5...
92265,The 7 Adventures of Sinbad,2010.0,NaN,action adventure fantasy,0.259381,https://a.ltrbxd.com/resized/film-poster/2/0/4...
868,Godzilla,2014.0,3.05,science fiction drama action,0.257236,https://a.ltrbxd.com/resized/film-poster/9/8/3...
7761,"Ebirah, Horror of the Deep",1966.0,2.98,science fiction action fantasy,0.253896,https://a.ltrbxd.com/resized/film-poster/4/9/8...
6324,"20,000 Leagues Under the Sea",1954.0,3.54,family science fiction adventure,0.252496,https://a.ltrbxd.com/resized/film-poster/5/1/8...
918,The Lost World: Jurassic Park,1997.0,3.08,science fiction action adventure,0.248406,https://a.ltrbxd.com/resized/sm/upload/ab/ir/x...
6284,"10,000 BC",2008.0,1.99,action adventure drama fantasy,0.245605,https://a.ltrbxd.com/resized/film-poster/4/7/9...
482505,King Kong,2016.0,NaN,NaN,0.245275,https://a.ltrbxd.com/resized/film-poster/1/1/8...
7138,Primal,2019.0,4.33,animation drama,0.245263,https://a.ltrbxd.com/resized/film-poster/5/6/5...
5436,Jungle,2017.0,3.18,adventure drama thriller,0.241311,https://a.ltrbxd.com/resized/sm/upload/a0/67/m...
761,Kong: Skull Island,2017.0,3.07,action adventure fantasy,0.240476,https://a.ltrbxd.com/resized/film-poster/2/2/0...
32713,The Lost Continent,1968.0,2.99,adventure fantasy,0.239932,https://a.ltrbxd.com/resized/film-poster/4/8/9...
7149,Congo,1995.0,2.59,science fiction adventure action,0.235854,https://a.ltrbxd.com/resized/film-poster/4/6/3...
10190,Cutthroat Island,1995.0,2.75,adventure action,0.231880,https://a.ltrbxd.com/resized/film-poster/5/1/0...
14156,The Deep,1977.0,3.02,adventure thriller mystery,0.231236,https://a.ltrbxd.com/resized/film-poster/3/9/0...

In [10]:
recommend("Casablanca")

,title,release_year,avg_rating,genres,similarity,poster_url
25696,Passage to Marseille,1944.0,3.33,adventure war,0.381235,https://a.ltrbxd.com/resized/film-poster/4/0/4...
399045,Casablanca (Takarazuka),2010.0,NaN,NaN,0.371032,https://a.ltrbxd.com/resized/film-poster/1/0/0...
40000,Arch of Triumph,1948.0,3.28,drama romance,0.280269,https://a.ltrbxd.com/resized/film-poster/2/4/0...
42122,Mission to Moscow,1943.0,3.05,drama war history,0.235505,https://a.ltrbxd.com/resized/film-poster/1/2/0...
4871,The Marriage of Maria Braun,1979.0,4.03,drama,0.222999,https://a.ltrbxd.com/resized/film-poster/5/1/4...
410105,Peer Gynt - 2. Teil: Peer Gynts Wanderjahre un...,1919.0,NaN,drama,0.221855,NaN
2104,Notorious,1946.0,4.09,thriller mystery romance,0.216587,https://a.ltrbxd.com/resized/film-poster/5/1/7...
302743,The Love Storm,1930.0,NaN,drama,0.214981,https://a.ltrbxd.com/resized/film-poster/2/1/6...
213086,The Coronation of King Charles IV,1916.0,NaN,documentary history,0.210855,https://a.ltrbxd.com/resized/film-poster/5/8/7...
20398,All Through the Night,1942.0,3.46,crime war comedy thriller action,0.210730,https://a.ltrbxd.com/resized/film-poster/2/7/3...
1597,Hiroshima Mon Amour,1959.0,4.18,drama romance history,0.209817,https://a.ltrbxd.com/resized/sm/upload/d4/0z/w...
343713,Schicksal,1925.0,NaN,drama,0.209701,NaN
7614,The Majestic,2001.0,3.26,romance drama,0.207191,https://a.ltrbxd.com/resized/sm/upload/7k/5z/s...
52993,Escape,1940.0,3.37,thriller drama,0.207027,https://a.ltrbxd.com/resized/film-poster/8/7/6...
10615,A Foreign Affair,1948.0,3.67,drama comedy romance,0.206328,https://a.ltrbxd.com/resized/film-poster/5/0/7...
33904,East/West,1999.0,3.42,drama romance,0.204156,https://a.ltrbxd.com/resized/film-poster/3/3/6...
279657,Bánk bán,1915.0,NaN,drama history,0.203102,NaN
4395,Journey to Italy,1954.0,3.82,romance drama,0.200811,https://a.ltrbxd.com/resized/film-poster/5/0/1...
274020,Le Comte Kostia,1925.0,NaN,history drama,0.200617,https://a.ltrbxd.com/resized/film-poster/6/1/9...
69453,Stolen Holiday,1937.0,3.25,romance drama,0.198289,https://a.ltrbxd.com/resized/film-poster/1/3/6...

In [11]:
recommend("Sholay")

,title,release_year,avg_rating,genres,similarity,poster_url
184212,Gunsmoke,NaN,NaN,NaN,0.328934,NaN
53685,Satte Pe Satta,1982.0,3.34,comedy,0.306330,https://a.ltrbxd.com/resized/film-poster/2/9/9...
52533,Seeta and Geeta,1972.0,3.40,adventure comedy romance,0.296259,https://a.ltrbxd.com/resized/film-poster/2/8/4...
46961,Aarakshan,2011.0,3.11,thriller drama,0.295034,https://a.ltrbxd.com/resized/film-poster/5/7/3...
207408,Pratiggya,1975.0,NaN,NaN,0.294293,https://a.ltrbxd.com/resized/film-poster/2/3/4...
202179,Cinema Cinema,1979.0,NaN,documentary music,0.293287,https://a.ltrbxd.com/resized/film-poster/3/1/7...
7126,Jonah Hex,2010.0,1.76,fantasy drama western thriller action,0.292509,https://a.ltrbxd.com/resized/film-poster/3/8/9...
156518,Nastik,1983.0,NaN,action,0.289564,https://a.ltrbxd.com/resized/film-poster/2/1/2...
23069,American Outlaws,2001.0,2.73,action western,0.280527,https://a.ltrbxd.com/resized/film-poster/4/3/8...
55574,Baabul,2006.0,2.94,family romance drama,0.276400,https://a.ltrbxd.com/resized/film-poster/1/7/3...
103502,Do Aur Do Paanch,1980.0,NaN,drama comedy action,0.275092,https://a.ltrbxd.com/resized/film-poster/1/1/6...
31185,"Adiós, Sabata",1970.0,3.10,western war action,0.272284,https://a.ltrbxd.com/resized/film-poster/5/8/2...
9432,The Professionals,1966.0,3.67,adventure action western,0.271889,https://a.ltrbxd.com/resized/film-poster/3/7/9...
211065,Chacha Bhatija,1977.0,NaN,NaN,0.269434,https://a.ltrbxd.com/resized/film-poster/3/4/4...
260449,Samraat,1982.0,NaN,adventure romance,0.268820,https://a.ltrbxd.com/resized/film-poster/3/1/4...
10166,Veer-Zaara,2004.0,3.82,romance drama,0.265987,https://a.ltrbxd.com/resized/film-poster/4/9/4...
150029,Desh Premee,1982.0,NaN,action drama,0.265196,https://a.ltrbxd.com/resized/film-poster/2/5/3...
63391,Trishul,1978.0,3.45,action drama family,0.264978,https://a.ltrbxd.com/resized/film-poster/8/6/9...
18743,Tears of the Black Tiger,2000.0,3.59,action comedy western romance,0.264910,https://a.ltrbxd.com/resized/film-poster/5/0/0...
2233,The Magnificent Seven,2016.0,3.10,western action adventure,0.264587,https://a.ltrbxd.com/resized/film-poster/2/6/2...

In [17]:
recommend("abcdef")

'Movie not found.'

In [19]:
test_movies = [
    "Interstellar",
    "Inception",
    "The Dark Knight",
    "Parasite",
    "Barbie",
    "Avengers: Endgame",
    "Dangal",
    "3 Idiots",
    "The Godfather",
    "Titanic",
    "abcdef"
]

success = 0
failed = 0

for movie in test_movies:

    result = recommend(movie)

    if isinstance(result, str):
        failed += 1
    else:
        success += 1

print(f"Successful : {success}")
print(f"Failed : {failed}")
print(f"Success Rate : {(success/(success+failed))*100:.2f}%")

Successful : 10
Failed : 1
Success Rate : 90.91%

In [20]:
genre_movies = [
    "Interstellar",      # Sci-Fi
    "The Godfather",     # Crime
    "Parasite",          # Thriller
    "Barbie",            # Comedy
    "Titanic",           # Romance
    "The Conjuring",     # Horror
    "Dangal"             # Sports
]

for movie in genre_movies:

    print("="*80)
    print(movie)
    print(recommend(movie).head(5))

================================================================================
Interstellar
        title  release_year  avg_rating  \
3839  Solaris        2002.0        3.25
5448   Aniara        2018.0        3.54
988      Moon        2009.0        3.86
1603  Contact        1997.0        3.78
7037   Vesper        2022.0        3.12

                                       genres  similarity  \
3839            mystery science fiction drama    0.479169
5448                    science fiction drama    0.467531
988                     science fiction drama    0.443856
1603            science fiction mystery drama    0.441785
7037  science fiction drama adventure fantasy    0.433533

                                             poster_url
3839  https://a.ltrbxd.com/resized/film-poster/5/0/5...
5448  https://a.ltrbxd.com/resized/film-poster/4/2/6...
988   https://a.ltrbxd.com/resized/sm/upload/1z/15/k...
1603  https://a.ltrbxd.com/resized/film-poster/5/1/4...
7037  https://a.ltrbxd.com/resized/film-poster/8/7/8...
================================================================================
The Godfather
                                     title  release_year  avg_rating  \
228                 The Godfather: Part II        1974.0        4.59
900                The Godfather: Part III        1990.0        3.46
36700  The Godfather Family: A Look Inside        1990.0        3.64
17901                           Blood Ties        2013.0        3.06
9971                       The Rain People        1969.0        3.58

                     genres  similarity  \
228             crime drama    0.523237
900    drama thriller crime    0.411862
36700  documentary tv movie    0.379458
17901  crime drama thriller    0.314173
9971                  drama    0.279803

                                              poster_url
228    https://a.ltrbxd.com/resized/film-poster/5/1/8...
900    https://a.ltrbxd.com/resized/film-poster/5/1/8...
36700  https://a.ltrbxd.com/resized/film-poster/9/8/7...
17901  https://a.ltrbxd.com/resized/film-poster/1/3/7...
9971   https://a.ltrbxd.com/resized/film-poster/7/1/3...
================================================================================
Parasite
                             title  release_year  avg_rating  \
58909         The Poet and the Boy        2017.0        3.28
116872         Officer of the Year        2011.0         NaN
227183             Black Honeymoon        2000.0         NaN
1837    Sympathy for Mr. Vengeance        2002.0        3.97
391566                Boy Director        2008.0         NaN

                        genres  similarity  \
58909                    drama    0.326025
116872           action comedy    0.322432
227183  thriller mystery drama    0.315872
1837     drama thriller action    0.296014
391566            family drama    0.293203

                                               poster_url
58909   https://a.ltrbxd.com/resized/film-poster/4/0/1...
116872  https://a.ltrbxd.com/resized/film-poster/5/7/8...
227183  https://a.ltrbxd.com/resized/film-poster/1/9/9...
1837    https://a.ltrbxd.com/resized/sm/upload/v7/7s/n...
391566  https://a.ltrbxd.com/resized/film-poster/4/9/9...
================================================================================
Barbie
                           title  release_year  avg_rating  \
670               Swiss Army Man        2016.0        3.66
1381   It's Such a Beautiful Day        2012.0        4.38
1955       Stranger Than Fiction        2006.0        3.61
11163        The Midnight Gospel        2020.0        4.33
77952                      Guilt        2019.0        3.54

                                       genres  similarity  \
670    drama fantasy comedy adventure romance    0.324742
1381                         comedy animation    0.292019
1955             drama fantasy romance comedy    0.285200
11163                mystery animation comedy    0.276632
77952                      comedy crime drama    0.276012

                                              poster_url
670    https://a.ltrbxd.com/resized/sm/upload/pp/ya/j...
1381   https://a.ltrbxd.com/resized/sm/upload/on/mj/o...
1955   https://a.ltrbxd.com/resized/film-poster/5/1/1...
11163  https://a.ltrbxd.com/resized/film-poster/7/9/4...
77952  https://a.ltrbxd.com/resized/film-poster/5/7/5...
================================================================================
Titanic
                        title  release_year  avg_rating  \
321681   A Fatherless America           NaN         NaN
13997     Ghosts of the Abyss        2003.0        3.28
18781                 Titanic        1953.0        3.26
130431  Titanic: 100 Years On        2012.0         NaN
4604                   Adrift        2018.0        3.13

                            genres  similarity  \
321681                         NaN    0.265394
13997                  documentary    0.261428
18781                drama romance    0.259104
130431                 documentary    0.238267
4604    thriller adventure romance    0.235812

                                               poster_url
321681                                                NaN
13997   https://a.ltrbxd.com/resized/film-poster/3/6/3...
18781   https://a.ltrbxd.com/resized/film-poster/4/1/5...
130431  https://a.ltrbxd.com/resized/film-poster/1/4/2...
4604    https://a.ltrbxd.com/resized/film-poster/3/6/2...
================================================================================
The Conjuring
                     title  release_year  avg_rating           genres  \
1678  Insidious: Chapter 2        2013.0        2.99  horror thriller
700              Insidious        2010.0        3.21  horror thriller
3264            The Medium        2021.0        3.37  horror thriller
33             The Shining        1980.0        4.24  horror thriller
701        The Conjuring 2        2016.0        3.36           horror

      similarity                                         poster_url
1678    0.449046  https://a.ltrbxd.com/resized/film-poster/7/6/6...
700     0.445077  https://a.ltrbxd.com/resized/sm/upload/te/ew/l...
3264    0.421822  https://a.ltrbxd.com/resized/film-poster/6/6/7...
33      0.411448  https://a.ltrbxd.com/resized/sm/upload/7s/m2/b...
701     0.410144  https://a.ltrbxd.com/resized/sm/upload/vu/cv/s...
================================================================================
Dangal
                    title  release_year  avg_rating            genres  \
18970          Dhobi Ghat        2010.0        3.59             drama
28075       Irudhi Suttru        2016.0        3.49      drama action
30010            Brothers        2015.0        2.73      drama action
13237                Ludo        2020.0        3.41      crime comedy
27109  Thugs of Hindostan        2018.0        2.24  action adventure

       similarity                                         poster_url
18970    0.280286  https://a.ltrbxd.com/resized/film-poster/1/1/2...
28075    0.247761  https://a.ltrbxd.com/resized/film-poster/2/8/8...
30010    0.222297  https://a.ltrbxd.com/resized/film-poster/2/5/7...
13237    0.222183  https://a.ltrbxd.com/resized/film-poster/5/8/3...
27109    0.220204  https://a.ltrbxd.com/resized/film-poster/4/0/3...

# Recommendation Model Evaluation

## Model Used
- TF-IDF Vectorization
- K-Nearest Neighbors (Cosine Distance)

## Dataset
- Total Movies: 577,523

## Results
- Recommendation Generation: Successful
- Duplicate Handling: Passed
- Invalid Movie Handling: Passed
- Genre-Based Testing: Passed
- Search Engine Integration: Passed

## Performance
- Average Response Time: 1.60 sec
- Fastest Response: 1.36 sec
- Slowest Response: 1.95 sec

## Future Improvements
- Optimize recommendation latency
- Add popularity score
- Hybrid recommendation model
- User-personalized recommendations