In [1]:
import pandas as pd

movies = pd.read_csv(
    "../dataset/processed/movieverse_master_dataset.csv"
)

movies.head()

C:\Users\HARIOM SUTHAR\AppData\Local\Temp\ipykernel_20100\3159022228.py:3: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv(

,movie_id,title,release_year,tagline,overview,runtime_minutes,avg_rating,genres,main_cast,poster_url,director,producer,languages,themes,countries,studios
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86,Comedy | Adventure,Margot Robbie as Barbie | Ryan Gosling as Ken ...,https://a.ltrbxd.com/resized/film-poster/2/7/7...,Greta Gerwig,Tom Ackerley | Margot Robbie | Robbie Brenner,English,Humanity and the world around us | Crude humor...,UK | USA,LuckyChap Entertainment | Heyday Films | NB/GG...
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56,Comedy | Thriller | Drama,Song Kang-ho as Kim Ki-taek | Lee Sun-kyun as ...,https://a.ltrbxd.com/resized/film-poster/4/2/6...,Bong Joon-ho,Jang Young-hwan | Kwak Sin-ae | Moon Yang-kwon,Korean | English | German,Humanity and the world around us | Intense vio...,South Korea,Barunson E&A
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30,Science Fiction | Adventure | Comedy | Action,Michelle Yeoh as Evelyn Wang | Ke Huy Quan as ...,https://a.ltrbxd.com/resized/film-poster/4/7/4...,Daniel Scheinert | Daniel Kwan,Joe Russo | Anthony Russo | Jonathan Wang,English | Cantonese | Chinese,Humanity and the world around us | Moving rela...,USA,IAC Films | AGBO | Ley Line Entertainment
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27,Drama,Edward Norton as Narrator | Brad Pitt as Tyler...,https://a.ltrbxd.com/resized/film-poster/5/1/5...,David Fincher,Ross Grayson Bell | Ceán Chaffin | Art Linson,English,Intense violence and sexual transgression | Hu...,Germany | USA,Fox 2000 Pictures | Regency Enterprises | The ...
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09,Drama | Comedy | Music | Romance,Ryan Gosling as Sebastian | Emma Stone as Mia ...,https://a.ltrbxd.com/resized/film-poster/2/4/0...,Damien Chazelle,Jordan Horowitz | Fred Berger | Marc Platt,English,Song and dance | Humanity and the world around...,Hong Kong | USA,Summit Entertainment | Black Label Media | Gil...

In [2]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570740 entries, 0 to 570739
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   movie_id         570740 non-null  int64
 1   title            570740 non-null  object
 2   release_year     514418 non-null  float64
 3   tagline          96105 non-null   object
 4   overview         438259 non-null  object
 5   runtime_minutes  389177 non-null  float64
 6   avg_rating       74215 non-null   float64
 7   genres           429421 non-null  object
 8   main_cast        431166 non-null  object
 9   poster_url       477312 non-null  object
 10  director         463912 non-null  object
 11  producer         194167 non-null  object
 12  languages        560038 non-null  object
 13  themes           23618 non-null   object
 14  countries        391314 non-null  object
 15  studios          295786 non-null  object
dtypes: float64(3), int64(1), object(12)
memory usage: 69.7+ MB

In [3]:

movies.shape

(570740, 16)

In [4]:
movies.columns.tolist()

['movie_id',
 'title',
 'release_year',
 'tagline',
 'overview',
 'runtime_minutes',
 'avg_rating',
 'genres',
 'main_cast',
 'poster_url',
 'director',
 'producer',
 'languages',
 'themes',
 'countries',
 'studios']

# 
MovieVerse Database Design

Tables

1. movies
2. users
3. ratings
4. reviews
5. watchlist
6. favorites
7. search_history
8. user_activity

| Column          | Type         |
| --------------- | ------------ |
| movie_id        | BIGINT       |
| title           | VARCHAR(255) |
| release_year    | YEAR         |
| tagline         | TEXT         |
| overview        | LONGTEXT     |
| runtime_minutes | INT          |
| avg_rating      | FLOAT        |
| genres          | TEXT         |
| main_cast       | LONGTEXT     |
| poster_url      | TEXT         |
| director        | TEXT         |
| producer        | TEXT         |
| languages       | VARCHAR(200) |
| countries       | VARCHAR(200) |
| studios         | TEXT         |
| themes          | TEXT         |

## User
user_id,
username,
email,
password_hash,
profile_image,
created_at,

## Ratings
rating_id,
user_id,
movie_id,
rating,
created_at,

## Reviews
review_id,
user_id,
movie_id,
review,
likes,
created_at,

## Watchlist
watchlist_id,
user_id,
movie_id,
added_at,

## Favorites
favorite_id,
user_id,
movie_id,
added_at,

## Search History
history_id
user_id
search_query
searched_at

In [6]:
columns_to_check = [
    "genres",
    "languages",
    "countries",
    "studios",
    "themes"
]

for column in columns_to_check:

    unique_values = (
        movies[column]
        .dropna()
        .str.split(" | ", regex=False)
        .explode()
        .nunique()
    )

    print(f"{column}: {unique_values:,} unique values")

genres: 19 unique values
languages: 187 unique values
countries: 239 unique values
studios: 117,627 unique values
themes: 109 unique values

## Genres Table

In [ ]:
genres_table = (
    movies["genres"]
    .dropna()
    .str.split(" | ", regex=False)
    .explode()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="genre_name")
)

genres_table.insert(0, "genre_id", range(1, len(genres_table) + 1))

genres_table.head()

In [8]:
genres_table.shape

(19, 2)

##  Save Genres Table

In [10]:
genres_table.to_csv(
    "../dataset/database/genres.csv",
    index=False
)

print("Genres Table Saved")

Genres Table Saved

## Genre Mapping Dictionary

In [11]:
genre_map = dict(
    zip(
        genres_table["genre_name"],
        genres_table["genre_id"]
    )
)

list(genre_map.items())[:5]

[('Action', 1),
 ('Adventure', 2),
 ('Animation', 3),
 ('Comedy', 4),
 ('Crime', 5)]

## Create Movie Genres Table

In [12]:
movie_genres = (
    movies[
        ["movie_id", "genres"]
    ]
    .dropna()
)

movie_genres["genres"] = movie_genres["genres"].str.split(" | ", regex=False)

movie_genres = movie_genres.explode("genres")

movie_genres["genre_id"] = movie_genres["genres"].map(genre_map)

movie_genres = movie_genres[
    ["movie_id", "genre_id"]
]

In [13]:
movie_genres.head(10)

   movie_id  genre_id
0   1000001         4
0   1000001         2
1   1000002         4
1   1000002        17
1   1000002         7
2   1000003        15
2   1000003         2
2   1000003         4
2   1000003         1
3   1000004         7

In [14]:
movie_genres.shape

(711419, 2)

In [15]:
movie_genres.duplicated().sum()

np.int64(0)

## Save

In [16]:
movie_genres.to_csv(
    "../dataset/database/movie_genres.csv",
    index=False
)

print("Movie Genres Saved")
print(movie_genres.shape)

Movie Genres Saved
(711419, 2)

## Languages Table

In [17]:
languages_table = (
    movies["languages"]
    .dropna()
    .str.split(" | ", regex=False)
    .explode()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="language_name")
)

languages_table.insert(
    0,
    "language_id",
    range(1, len(languages_table) + 1)
)

languages_table.head()

   language_id language_name
0            1        Abkhaz
1            2          Afar
2            3     Afrikaans
3            4          Akan
4            5      Albanian

## Save Languages

In [18]:
languages_table.to_csv(
    "../dataset/database/languages.csv",
    index=False
)

print("Languages Table Saved")
print(languages_table.shape)

Languages Table Saved
(187, 2)

## Create Language Mapping

In [19]:
language_map = dict(
    zip(
        languages_table["language_name"],
        languages_table["language_id"]
    )
)

## Movie Languages

In [20]:
movie_languages = (
    movies[
        ["movie_id", "languages"]
    ]
    .dropna()
)

movie_languages["languages"] = (
    movie_languages["languages"]
    .str.split(" | ", regex=False)
)

movie_languages = movie_languages.explode("languages")

movie_languages["language_id"] = (
    movie_languages["languages"]
    .map(language_map)
)

movie_languages = movie_languages[
    [
        "movie_id",
        "language_id"
    ]
]

In [21]:
movie_languages.head()

   movie_id  language_id
0   1000001           42
1   1000002           87
1   1000002           42
1   1000002           54
2   1000003           42

In [22]:
movie_languages.shape

(625779, 2)

In [23]:
movie_languages.duplicated().sum()

np.int64(0)

## Save

In [24]:
movie_languages.to_csv(
    "../dataset/database/movie_languages.csv",
    index=False
)

print("Movie Languages Saved")
print(movie_languages.shape)

Movie Languages Saved
(625779, 2)

## Countries Table

In [25]:
countries_table = (
    movies["countries"]
    .dropna()
    .str.split(" | ", regex=False)
    .explode()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="country_name")
)

countries_table.insert(
    0,
    "country_id",
    range(1, len(countries_table) + 1)
)

countries_table.head()

   country_id    country_name
0           1     Afghanistan
1           2         Albania
2           3         Algeria
3           4  American Samoa
4           5         Andorra

## Save Countries

In [26]:
countries_table.to_csv(
    "../dataset/database/countries.csv",
    index=False
)

print("Countries Table Saved")
print(countries_table.shape)

Countries Table Saved
(239, 2)

## Country Mapping

In [27]:
country_map = dict(
    zip(
        countries_table["country_name"],
        countries_table["country_id"]
    )
)

## Movie Countries

In [28]:
movie_countries = (
    movies[
        ["movie_id", "countries"]
    ]
    .dropna()
)

movie_countries["countries"] = (
    movie_countries["countries"]
    .str.split(" | ", regex=False)
)

movie_countries = movie_countries.explode("countries")

movie_countries["country_id"] = (
    movie_countries["countries"]
    .map(country_map)
)

movie_countries = movie_countries[
    [
        "movie_id",
        "country_id"
    ]
]

In [29]:
movie_countries.head()

   movie_id  country_id
0   1000001         220
0   1000001         222
1   1000002         196
2   1000003         222
3   1000004          82

In [30]:
movie_countries.shape

(457747, 2)

In [31]:
movie_countries.duplicated().sum()

np.int64(0)

## Save

In [32]:
movie_countries.to_csv(
    "../dataset/database/movie_countries.csv",
    index=False
)

print("Movie Countries Saved")
print(movie_countries.shape)

Movie Countries Saved
(457747, 2)

## Themes

In [33]:
themes_table = (
    movies["themes"]
    .dropna()
    .str.split(" | ", regex=False)
    .explode()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="theme_name")
)

themes_table.insert(
    0,
    "theme_id",
    range(1, len(themes_table) + 1)
)

themes_table.head()

   theme_id                                  theme_name
0         1             Action comedy and silly heroics
1         2         Action-packed space and alien sagas
2         3  Adorable animals and heartwarming families
3         4      Adrenaline-fueled action and fast cars
4         5              Air pilot heroism and survival

## Save

In [34]:
themes_table.to_csv(
    "../dataset/database/themes.csv",
    index=False
)

print("Themes Table Saved")
print(themes_table.shape)

Themes Table Saved
(109, 2)

## Theme Mapping

In [35]:
theme_map = dict(
    zip(
        themes_table["theme_name"],
        themes_table["theme_id"]
    )
)

##  Movie Themes

In [36]:
movie_themes = (
    movies[
        ["movie_id", "themes"]
    ]
    .dropna()
)

movie_themes["themes"] = (
    movie_themes["themes"]
    .str.split(" | ", regex=False)
)

movie_themes = movie_themes.explode("themes")

movie_themes["theme_id"] = (
    movie_themes["themes"]
    .map(theme_map)
)

movie_themes = movie_themes[
    [
        "movie_id",
        "theme_id"
    ]
]

## Save

In [37]:
movie_themes.to_csv(
    "../dataset/database/movie_themes.csv",
    index=False
)

print("Movie Themes Saved")
print(movie_themes.shape)

Movie Themes Saved
(124957, 2)

## Extract Every Actor

In [40]:
cast_data = (
    movies[
        ["movie_id", "main_cast"]
    ]
    .dropna()
)

cast_data["main_cast"] = (
    cast_data["main_cast"]
    .str.split(" | ", regex=False)
)

cast_data = cast_data.explode("main_cast")

cast_data.head()

   movie_id                   main_cast
0   1000001     Margot Robbie as Barbie
0   1000001         Ryan Gosling as Ken
0   1000001   America Ferrera as Gloria
0   1000001  Ariana Greenblatt as Sasha
0   1000001          Issa Rae as Barbie

## Split Actor & Role

In [41]:
cast_data[
    ["actor_name", "role"]
] = cast_data["main_cast"].str.split(
    " as ",
    n=1,
    expand=True
)

cast_data.head()

   movie_id                   main_cast         actor_name    role
0   1000001     Margot Robbie as Barbie      Margot Robbie  Barbie
0   1000001         Ryan Gosling as Ken       Ryan Gosling     Ken
0   1000001   America Ferrera as Gloria    America Ferrera  Gloria
0   1000001  Ariana Greenblatt as Sasha  Ariana Greenblatt   Sasha
0   1000001          Issa Rae as Barbie           Issa Rae  Barbie

In [42]:
cast_data.isna().sum()

movie_id       0
main_cast      0
actor_name     0
role          56
dtype: int64

## Create Actors Table

In [43]:
actors_table = (
    cast_data["actor_name"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="actor_name")
)

actors_table.insert(
    0,
    "actor_id",
    range(1, len(actors_table)+1)
)

actors_table.head()

   actor_id                      actor_name
0         1
1         2     !'aru Ikhuisi Piet Berendse
2         3  "Ben" Benjamin Henry [Present]
3         4            "Big" Sam Amoakoatta
4         5                "Crazy" Bob Cook

In [44]:
actors_table.shape

(683414, 2)

In [46]:
actors_table.sample(20)

        actor_id                 actor_name
212647    212648               Gene Gerrard
132229    132230            Damiano Chionni
352984    352985            Kundan Bhardwaj
72534      72535       Bernadette O'Farrell
427966    427967                Mayu Sagara
91718      91719                Cai Wenjing
474562    474563                Nimon Muçaj
556097    556098           Samantha Essence
98089      98090             Carol Halstead
655030    655031              Winona Winter
35560      35561           Andreas Lugmayer
308544    308545               Jorge Patiño
663326    663327                Yoo Je-yoon
427034    427035          Maximilian Schell
499169    499170  Peck Premanat Suwannannon
353187    353188           Kurnia Alexander
215361    215362             Georgia Anesti
24519      24520                      Alies
464957    464958            Natsuki Takaoka
154238    154239               Dilnaz Irani

## save

In [47]:
actors_table.to_csv(
    "../dataset/database/actors.csv",
    index=False
)

print("Actors Table Saved")
print(actors_table.shape)

Actors Table Saved
(683414, 2)

##Actor Mapping

In [48]:
actor_map = dict(
    zip(
        actors_table["actor_name"],
        actors_table["actor_id"]
    )
)

In [49]:
##Create Movie Actors Table

In [50]:
movie_actors = cast_data.copy()

movie_actors["actor_id"] = (
    movie_actors["actor_name"]
    .map(actor_map)
)

movie_actors = movie_actors[
    [
        "movie_id",
        "actor_id",
        "role"
    ]
]

movie_actors.head()

   movie_id  actor_id    role
0   1000001    402997  Barbie
0   1000001    549292     Ken
0   1000001     29673  Gloria
0   1000001     52883   Sasha
0   1000001    262218  Barbie

In [51]:
movie_actors.duplicated().sum()

np.int64(253)

In [52]:
##save

In [53]:
movie_actors.to_csv(
    "../dataset/database/movie_actors.csv",
    index=False
)

print("Movie Actors Saved")
print(movie_actors.shape)

Movie Actors Saved
(2441665, 3)

In [54]:
actors_table["actor_name"] = actors_table["actor_name"].str.strip()

In [55]:
actors_table["actor_name"].duplicated().sum()

np.int64(0)

In [56]:
## Directors Table

In [57]:
directors_table = (
    movies["director"]
    .dropna()
    .str.split(" | ", regex=False)
    .explode()
    .str.strip()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name="director_name")
)

directors_table.insert(
    0,
    "director_id",
    range(1, len(directors_table) + 1)
)

directors_table.head()

   director_id           director_name
0            1                 $NAPGOD
1            2        'Evil' Ted Smith
2            3    'Madurai' Thirumaran
3            4  'Om' Rakesh Chaturvedi
4            5    'Ronnie' Romance Jr.

In [58]:
## save

In [59]:
directors_table.to_csv(
    "../dataset/database/directors.csv",
    index=False
)

print("Directors Saved")
print(directors_table.shape)

Directors Saved
(192630, 2)

In [60]:
#Mapping

In [61]:
director_map = dict(
    zip(
        directors_table["director_name"],
        directors_table["director_id"]
    )
)

In [62]:
## Movie Directors

In [63]:
movie_directors = (
    movies[
        ["movie_id", "director"]
    ]
    .dropna()
)

movie_directors["director"] = (
    movie_directors["director"]
    .str.split(" | ", regex=False)
)

movie_directors = movie_directors.explode("director")

movie_directors["director"] = (
    movie_directors["director"]
    .str.strip()
)

movie_directors["director_id"] = (
    movie_directors["director"]
    .map(director_map)
)

movie_directors = movie_directors[
    [
        "movie_id",
        "director_id"
    ]
]

In [64]:
##save

In [65]:
movie_directors.to_csv(
    "../dataset/database/movie_directors.csv",
    index=False
)

print("Movie Directors Saved")
print(movie_directors.shape)

Movie Directors Saved
(533273, 2)

In [66]:
columns = [
    "title",
    "genres",
    "main_cast",
    "director",
    "producer",
    "languages",
    "countries",
    "studios",
    "themes"
]

for col in columns:

    count = movies[col].fillna("").str.strip().eq("").sum()

    print(f"{col}: {count:,}")

title: 8
genres: 142,020
main_cast: 140,183
director: 108,184
producer: 380,895
languages: 10,778
countries: 180,054
studios: 277,271
themes: 553,190

In [67]:
check_values = [
    "Unknown",
    "unknown",
    "N/A",
    "NA",
    "None",
    "-"
]

for col in columns:

    print(f"\n----- {col} -----")

    for value in check_values:

        count = movies[col].fillna("").str.contains(
            value,
            case=False,
            regex=False
        ).sum()

        if count > 0:
            print(value, count)

----- title -----
Unknown 314
unknown 314
N/A 5
NA 38333
None 68
- 36955

----- genres -----

----- main_cast -----
Unknown 61
unknown 61
N/A 57
NA 224578
None 267
- 67107

----- director -----
Unknown 4
unknown 4
NA 40290
None 129
- 23123

----- producer -----
NA 27640
None 38
- 10946

----- languages -----
NA 2537
- 952

----- countries -----
NA 31037
- 22

----- studios -----
Unknown 43
unknown 43
N/A 7
NA 25858
None 22
- 15860

----- themes -----
NA 10321
- 9449

In [68]:
for col in columns:

    count = (
        movies[col]
        .dropna()
        .str.startswith(" ")
        .sum()
        +
        movies[col]
        .dropna()
        .str.endswith(" ")
        .sum()
    )

    print(col, count)

title 0
genres 0
main_cast 137878
director 0
producer 0
languages 0
countries 0
studios 0
themes 0

In [69]:
movies["movie_id"].duplicated().sum()

np.int64(0)

In [70]:
movies.duplicated(
    subset=["title", "release_year"]
).sum()

np.int64(8602)

In [71]:
movies["runtime_minutes"].describe()

count    395953.000000
mean        108.257210
std         204.929849
min          60.000000
25%          81.000000
50%          91.000000
75%         105.000000
max       72000.000000
Name: runtime_minutes, dtype: float64

In [72]:
movies.loc[
    movies["runtime_minutes"] > 300,
    [
        "movie_id",
        "title",
        "runtime_minutes"
    ]
].head(20)

      movie_id                                       title  runtime_minutes
401    1000402                          The Queen's Gambit            393.0
454    1000455                                  Squid Game            495.0
514    1000515                                 WandaVision            350.0
646    1000648                                        Loki            615.0
652    1000654                               Normal People            342.0
685    1000687                                   Chernobyl            327.0
939    1000941                                        BEEF            351.0
1001   1001003           The Falcon and the Winter Soldier            330.0
1091   1001094                  The Haunting of Hill House            575.0
1453   1001459                      Twin Peaks: The Return           1014.0
1537   1001543                     Neon Genesis Evangelion            615.0
1629   1001636                                Cowboy Bebop            625.0
1696   1001704                               Sharp Objects            422.0
1706   1001714                   The Haunting of Bly Manor            494.0
1733   1001744                               Midnight Mass            448.0
1789   1001802  Dahmer – Monster: The Jeffrey Dahmer Story            534.0
1953   1001969                             Big Little Lies            702.0
1967   1001983                            Band of Brothers            594.0
1968   1001984                                     One Day            394.0
2067   1002084                   She-Hulk: Attorney at Law            309.0

In [73]:
movies["avg_rating"].describe()

count    75890.000000
mean         3.216090
std          0.431998
min          0.880000
25%          2.970000
50%          3.270000
75%          3.500000
max          4.690000
Name: avg_rating, dtype: float64

In [74]:
movies.loc[
    movies["avg_rating"] > 5
]

Empty DataFrame
Columns: [movie_id, title, release_year, tagline, overview, runtime_minutes, avg_rating, genres, main_cast, poster_url, director, producer, languages, themes, countries, studios]
Index: []

In [75]:
actors_table["actor_name"] = (
    actors_table["actor_name"]
    .str.strip()
)

actors_table["actor_name"].duplicated().sum()

np.int64(0)

In [76]:
directors_table["director_name"] = (
    directors_table["director_name"]
    .str.strip()
)

directors_table["director_name"].duplicated().sum()

np.int64(0)

In [77]:
movies[
    [
        "title",
        "release_year",
        "languages",
        "genres"
    ]
].isna().sum()

title                8
release_year     56494
languages        10778
genres          142020
dtype: int64

In [78]:
columns = [
    "genres",
    "main_cast",
    "director",
    "producer",
    "languages",
    "countries",
    "studios",
    "themes"
]

placeholders = [
    "Unknown",
    "N/A",
    "None",
    "-"
]

for col in columns:

    movies[col] = movies[col].replace(placeholders, pd.NA)

In [79]:
for col in columns:

    movies[col] = (
        movies[col]
        .replace(r'^\s*$', pd.NA, regex=True)
    )

In [80]:
movies = movies.dropna(
    subset=["title"]
)

In [81]:
movies.to_csv(
    "../dataset/processed/movieverse_master_dataset.csv",
    index=False
)

print("Final Clean Dataset Saved")
print(movies.shape)

Final Clean Dataset Saved
(577515, 16)

In [5]:

 genres = (
    movies["genres"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

genres = genres.to_frame(name="genre_name")
genres["genre_id"] = range(1, len(genres) + 1)

genres = genres[["genre_id", "genre_name"]]

genres.to_csv(
    "../dataset/processed/genres.csv",
    index=False
)

## Genres Table

In [6]:
genres = (
    movies["genres"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

genres = genres[genres != ""]

genres = (
    genres.drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

genres = genres.to_frame(name="genre_name")

genres["genre_id"] = range(1, len(genres) + 1)

genres = genres[["genre_id", "genre_name"]]

genres.to_csv(
    "../dataset/processed/genres.csv",
    index=False
)

print(genres.shape)
genres.head()

(19, 2)

   genre_id genre_name
0         1     Action
1         2  Adventure
2         3  Animation
3         4     Comedy
4         5      Crime

## Genre Mapping Dictionary

In [7]:
genre_map = dict(
    zip(genres["genre_name"], genres["genre_id"])
)

## Movie Genres Table

In [8]:
movie_genres = (
    movies[["movie_id", "genres"]]
    .dropna(subset=["genres"])
)

movie_genres["genres"] = (
    movie_genres["genres"]
    .str.split("|")
)

movie_genres = movie_genres.explode("genres")

movie_genres["genres"] = (
    movie_genres["genres"]
    .str.strip()
)

movie_genres = movie_genres[
    movie_genres["genres"] != ""
]

movie_genres["genre_id"] = (
    movie_genres["genres"]
    .map(genre_map)
)

movie_genres = movie_genres[
    ["movie_id", "genre_id"]
].drop_duplicates()

movie_genres.to_csv(
    "../dataset/processed/movie_genres.csv",
    index=False
)

print(movie_genres.shape)
movie_genres.head()

(701706, 2)

   movie_id  genre_id
0   1000001         4
0   1000001         2
1   1000002         4
1   1000002        17
1   1000002         7

## Languages Table

In [10]:
languages = (
    movies["languages"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

languages = languages[languages != ""]

languages = (
    languages.drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

languages = languages.to_frame(name="language_name")

languages["language_id"] = range(1, len(languages) + 1)

languages = languages[
    ["language_id", "language_name"]
]

languages.to_csv(
    "../dataset/processed/languages.csv",
    index=False
)

print("Languages Saved")
print(languages.shape)

languages.head()

Languages Saved
(187, 2)

   language_id language_name
0            1        Abkhaz
1            2          Afar
2            3     Afrikaans
3            4          Akan
4            5      Albanian

## Language Mapping

In [11]:
language_map = dict(
    zip(
        languages["language_name"],
        languages["language_id"]
    )
)

## Movie Languages

In [12]:
movie_languages = (
    movies[
        ["movie_id", "languages"]
    ]
    .dropna(subset=["languages"])
)

movie_languages["languages"] = (
    movie_languages["languages"]
    .str.split("|")
)

movie_languages = movie_languages.explode(
    "languages"
)

movie_languages["languages"] = (
    movie_languages["languages"]
    .str.strip()
)

movie_languages = movie_languages[
    movie_languages["languages"] != ""
]

movie_languages["language_id"] = (
    movie_languages["languages"]
    .map(language_map)
)

movie_languages = (
    movie_languages[
        ["movie_id", "language_id"]
    ]
    .drop_duplicates()
)

movie_languages.to_csv(
    "../dataset/processed/movie_languages.csv",
    index=False
)

print("Movie Languages Saved")
print(movie_languages.shape)

movie_languages.head()

Movie Languages Saved
(618227, 2)

   movie_id  language_id
0   1000001           42
1   1000002           87
1   1000002           42
1   1000002           54
2   1000003           42

## Countries Table

In [14]:
countries = (
    movies["countries"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

countries = countries[countries != ""]

countries = (
    countries
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

countries = countries.to_frame(name="country_name")

countries["country_id"] = range(1, len(countries) + 1)

countries = countries[
    ["country_id", "country_name"]
]

countries.to_csv(
    "../dataset/processed/countries.csv",
    index=False
)

print("Countries Saved")
print(countries.shape)

countries.head()

Countries Saved
(239, 2)

   country_id    country_name
0           1     Afghanistan
1           2         Albania
2           3         Algeria
3           4  American Samoa
4           5         Andorra

## Country Mapping

In [15]:
country_map = dict(
    zip(
        countries["country_name"],
        countries["country_id"]
    )
)

## movie countries

In [17]:
movie_countries = (
    movies[
        ["movie_id", "countries"]
    ]
    .dropna(subset=["countries"])
)

movie_countries["countries"] = (
    movie_countries["countries"]
    .str.split("|")
)

movie_countries = movie_countries.explode(
    "countries"
)

movie_countries["countries"] = (
    movie_countries["countries"]
    .str.strip()
)

movie_countries = movie_countries[
    movie_countries["countries"] != ""
]

movie_countries["country_id"] = (
    movie_countries["countries"]
    .map(country_map)
)

movie_countries = (
    movie_countries[
        ["movie_id", "country_id"]
    ]
    .drop_duplicates()
)

movie_countries.to_csv(
    "../dataset/processed/movie_countries.csv",
    index=False
)

print("Movie Countries Saved")
print(movie_countries.shape)

movie_countries.head()

Movie Countries Saved
(450783, 2)

   movie_id  country_id
0   1000001         220
0   1000001         222
1   1000002         196
2   1000003         222
3   1000004          82

## Themes Table

In [18]:
themes = (
    movies["themes"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

themes = themes[themes != ""]

themes = (
    themes
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

themes = themes.to_frame(name="theme_name")

themes["theme_id"] = range(1, len(themes) + 1)

themes = themes[
    ["theme_id", "theme_name"]
]

themes.to_csv(
    "../dataset/processed/themes.csv",
    index=False
)

print("Themes Saved")
print(themes.shape)

themes.head()

Themes Saved
(109, 2)

   theme_id                                  theme_name
0         1             Action comedy and silly heroics
1         2         Action-packed space and alien sagas
2         3  Adorable animals and heartwarming families
3         4      Adrenaline-fueled action and fast cars
4         5              Air pilot heroism and survival

## Theme Mapping

In [19]:
theme_map = dict(
    zip(
        themes["theme_name"],
        themes["theme_id"]
    )
)

## Movie Themes

In [20]:
movie_themes = (
    movies[
        ["movie_id", "themes"]
    ]
    .dropna(subset=["themes"])
)

movie_themes["themes"] = (
    movie_themes["themes"]
    .str.split("|")
)

movie_themes = movie_themes.explode(
    "themes"
)

movie_themes["themes"] = (
    movie_themes["themes"]
    .str.strip()
)

movie_themes = movie_themes[
    movie_themes["themes"] != ""
]

movie_themes["theme_id"] = (
    movie_themes["themes"]
    .map(theme_map)
)

movie_themes = (
    movie_themes[
        ["movie_id", "theme_id"]
    ]
    .drop_duplicates()
)

movie_themes.to_csv(
    "../dataset/processed/movie_themes.csv",
    index=False
)

print("Movie Themes Saved")
print(movie_themes.shape)

movie_themes.head()

Movie Themes Saved
(121840, 2)

   movie_id  theme_id
0   1000001        57
0   1000001        19
0   1000001        71
0   1000001        26
0   1000001        91

## Actors Table

In [21]:
actors = (
    movies["main_cast"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

actors = actors[actors != ""]

actors = (
    actors
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

actors = actors.to_frame(name="actor_name")

actors["actor_id"] = range(1, len(actors) + 1)

actors = actors[
    ["actor_id", "actor_name"]
]

actors.to_csv(
    "../dataset/processed/actors.csv",
    index=False
)

print("Actors Saved")
print(actors.shape)

actors.head()

Actors Saved
(1956153, 2)

   actor_id                                    actor_name
0         1        !'aru Ikhuisi Piet Berendse as Himself
1         2  "Big" Sam Amoakoatta as "Big" Sam Amoakoatta
2         3                   "Crazy" Bob Cook as Himself
3         4                   "Cuiri" Cristino Ramírez as
4         5                        "Fast" Eddie Clarke as

## Actor Mapping

In [22]:
actor_map = dict(
    zip(
        actors["actor_name"],
        actors["actor_id"]
    )
)

## Movie Actors Table

In [23]:
movie_actors = (
    movies[
        ["movie_id", "main_cast"]
    ]
    .dropna(subset=["main_cast"])
)

movie_actors["main_cast"] = (
    movie_actors["main_cast"]
    .str.split("|")
)

movie_actors = movie_actors.explode(
    "main_cast"
)

movie_actors["main_cast"] = (
    movie_actors["main_cast"]
    .str.strip()
)

movie_actors = movie_actors[
    movie_actors["main_cast"] != ""
]

movie_actors["actor_id"] = (
    movie_actors["main_cast"]
    .map(actor_map)
)

movie_actors["role"] = None

movie_actors = (
    movie_actors[
        ["movie_id", "actor_id", "role"]
    ]
    .drop_duplicates()
)

movie_actors.to_csv(
    "../dataset/processed/movie_actors.csv",
    index=False
)

print("Movie Actors Saved")
print(movie_actors.shape)

movie_actors.head()

Movie Actors Saved
(2403077, 3)

   movie_id  actor_id  role
0   1000001   1159826  None
0   1000001   1584639  None
0   1000001     77412  None
0   1000001    142074  None
0   1000001    750514  None

## Directors Table

In [24]:
directors = (
    movies["director"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

directors = directors[directors != ""]

directors = (
    directors
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

directors = directors.to_frame(name="director_name")

directors["director_id"] = range(1, len(directors) + 1)

directors = directors[
    ["director_id", "director_name"]
]

directors.to_csv(
    "../dataset/processed/directors.csv",
    index=False
)

print("Directors Saved")
print(directors.shape)

directors.head()

Directors Saved
(190909, 2)

   director_id           director_name
0            1                 $NAPGOD
1            2        'Evil' Ted Smith
2            3    'Madurai' Thirumaran
3            4  'Om' Rakesh Chaturvedi
4            5    'Ronnie' Romance Jr.

## Director Mapping

In [25]:
director_map = dict(
    zip(
        directors["director_name"],
        directors["director_id"]
    )
)

## Movie Directors Table

In [26]:
movie_directors = (
    movies[
        ["movie_id", "director"]
    ]
    .dropna(subset=["director"])
)

movie_directors["director"] = (
    movie_directors["director"]
    .str.split("|")
)

movie_directors = movie_directors.explode(
    "director"
)

movie_directors["director"] = (
    movie_directors["director"]
    .str.strip()
)

movie_directors = movie_directors[
    movie_directors["director"] != ""
]

movie_directors["director_id"] = (
    movie_directors["director"]
    .map(director_map)
)

movie_directors = (
    movie_directors[
        ["movie_id", "director_id"]
    ]
    .drop_duplicates()
)

movie_directors.to_csv(
    "../dataset/processed/movie_directors.csv",
    index=False
)

print("Movie Directors Saved")
print(movie_directors.shape)

movie_directors.head()

Movie Directors Saved
(521821, 2)

   movie_id  director_id
0   1000001        62449
1   1000002        22162
2   1000003        37428
2   1000003        37133
3   1000004        39334

# Producers Table

In [27]:
producers = (
    movies["producer"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

producers = producers[producers != ""]

producers = (
    producers
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

producers = producers.to_frame(name="producer_name")

producers["producer_id"] = range(1, len(producers) + 1)

producers = producers[
    ["producer_id", "producer_name"]
]

producers.to_csv(
    "../dataset/processed/producers.csv",
    index=False
)

print("Producers Saved")
print(producers.shape)

producers.head()

Producers Saved
(145012, 2)

   producer_id     producer_name
0            1    "Menito" Acuña
1            2  ''Knife'' Sotelo
2            3   'Aha Punana Leo
3            4       'By' Dunham
4            5  'Evil' Ted Smith

## Producer Mapping

In [28]:
producer_map = dict(
    zip(
        producers["producer_name"],
        producers["producer_id"]
    )
)

## Movie Producers Table

In [29]:
movie_producers = (
    movies[
        ["movie_id", "producer"]
    ]
    .dropna(subset=["producer"])
)

movie_producers["producer"] = (
    movie_producers["producer"]
    .str.split("|")
)

movie_producers = movie_producers.explode(
    "producer"
)

movie_producers["producer"] = (
    movie_producers["producer"]
    .str.strip()
)

movie_producers = movie_producers[
    movie_producers["producer"] != ""
]

movie_producers["producer_id"] = (
    movie_producers["producer"]
    .map(producer_map)
)

movie_producers = (
    movie_producers[
        ["movie_id", "producer_id"]
    ]
    .drop_duplicates()
)

movie_producers.to_csv(
    "../dataset/processed/movie_producers.csv",
    index=False
)

print("Movie Producers Saved")
print(movie_producers.shape)

movie_producers.head()

Movie Producers Saved
(342503, 2)

   movie_id  producer_id
0   1000001       133751
0   1000001        86137
0   1000001       114146
1   1000002        58490
1   1000002        76482

In [30]:
actors["actor_name"].str.len().max()

277

In [31]:
print(
    movies["main_cast"]
    .str.split("|")
    .explode()
    .str.strip()
    .duplicated()
    .sum()
)

586748

In [32]:
actors = (
    movies["main_cast"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
)

print("Total:", len(actors))
print("Unique:", actors.nunique())

Total: 2403328
Unique: 1956153

In [33]:
dup = actors[actors.duplicated("actor_name", keep=False)]

print(dup.shape)
print(dup[dup["actor_name"].str.contains("Weird Al", case=False, na=False)])

TypeError: Series.duplicated() got multiple values for argument 'keep'

In [34]:
type(actors)

pandas.core.series.Series

In [37]:
import pandas as pd

actors = pd.read_csv("../dataset/processed/actors.csv")

print(type(actors))
print(actors.columns)

<class 'pandas.core.frame.DataFrame'>
Index(['actor_id', 'actor_name'], dtype='object')

In [38]:
dup = actors[actors.duplicated(subset=["actor_name"], keep=False)]

print("Duplicate rows:", len(dup))

print(
    dup[
        dup["actor_name"].str.contains(
            "Weird Al",
            case=False,
            na=False
        )
    ]
)

Duplicate rows: 0
Empty DataFrame
Columns: [actor_id, actor_name]
Index: []